GET http://localhost:5050/authors

#####
GET http://localhost:5050/authors/byName?authorName=Matteo

#####
POST http://localhost:5050/authors HTTP/1.1
Content-Type: application/json

{
    "name": "Gerry",
    "surname": "Scotti",
    "password": "gerryscotti",
    "email": "gerryscotti@gmail.com",
    "dob": "16/12/1985",
    "avatar": "https://picsum.photos/200/200"
}

#####
GET http://localhost:5050/authors/64b04d62fa5f1ec32a47d2fc/posts