GET http://localhost:5050/posts

#####

POST http://localhost:5050/posts HTTP/1.1
Content-Type: application/json

{
    "category": "Student Stories",
    "title": "I was a salesman 6 months ago, and now I am a professional web developer",
    "cover": "https://imgur.com/DZf0S5G.jpg",
    "readTime": {
        "value": 2,
        "unit": "minute"
    },
    "author":{
        "name": "Bri Cho",
        "avatar": "https://imgur.com/ZsavJxA.jpg"
    },
    "content": "sono un content di prova 4"
}

#####
GET http://localhost:5050/posts/64ac5fcea2bb614e39159350

#####
PATCH http://localhost:5050/posts/64ac5fcea2bb614e39159350 HTTP/1.1
Content-Type: application/json

{
    "content":"sono un content modificato"
}

#####
DELETE http://localhost:5050/posts/64aee78e7de593a71820d870 